tasks:
  - init: yarn install && cd .infra && docker compose pull
    command: cd .infra && docker compose up -d

ports:
  - name: Grafana
    port: 30003
  - name: Jaeger
    port: 16686
  # Ignore all other open ports
  - port: 3200-30002
    onOpen: ignore